### PR TITLE
update for v1.3.3.

### PR DESCRIPTION
**Pull request by bhazelton**
Add libgfortran requrirements for testing.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bhazelton** [comment]
@conda-forge-admin, please rerender

**Comment by pkgw** [comment]
I think some extra selectors (the bits like `# [linux]` in meta.yaml) might be needed with your changes, since the different platforms have different sets of compiler support libraries (such as libgfortran).

But — I think I'm close to being able to merge the "rebuild" PR, and I'm pretty sure that change will make the build problem here go away.

**Comment by bhazelton** [comment]
Ok, then I'll stop thrashing and wait for your solution. Thanks!

**Comment by pkgw** [comment]
Sigh, I'm pretty stumped on a problem that was revealed in the rebuild PR. Want me to take a look at this one in isolation?

**Comment by bhazelton** [comment]
Sure! Thank you!

**Comment by pkgw** [comment]
Dealt with in #8.

**Pull request closed without merging**
